export const abbreviations: Record<string, string> = {
  independiente: 'ind.',
  atletico: 'atl.',
  atlético: 'atl.',
  deportivo: 'dep.',
  universidad: 'univ.',
  sporting: 'sp.',
  internacional: 'inter.',
  nacional: 'nac.',
  portuguesa: 'port.',
  revolution: 'rev.',
  galaxy: 'gal.',
  vancouver: 'van.',
  minnesota: 'minn.',
  earthquakes: 'eq.',
  guadalajara: 'gdl.',
  central: 'cent.',
  santiago: 'snt.',
}
