export interface Country {
  name: string
  nameCode: string
  code: string | null
  flag: string | null
}

export const COUNTRIES: Country[] = [
  // Países con ligas y copas relevantes
  {
    name: 'Argentina',
    nameCode: 'argentina',
    code: 'AR',
    flag: 'https://media.api-sports.io/flags/ar.svg',
  },
  {
    name: 'Belgium',
    nameCode: 'belgium',
    code: 'BE',
    flag: 'https://media.api-sports.io/flags/be.svg',
  },
  {
    name: 'Bolivia',
    nameCode: 'bolivia',
    code: 'BO',
    flag: 'https://media.api-sports.io/flags/bo.svg',
  },
  {
    name: 'Brazil',
    nameCode: 'brazil',
    code: 'BR',
    flag: 'https://media.api-sports.io/flags/br.svg',
  },
  {
    name: 'Chile',
    nameCode: 'chile',
    code: 'CL',
    flag: 'https://media.api-sports.io/flags/cl.svg',
  },
  {
    name: 'Colombia',
    nameCode: 'colombia',
    code: 'CO',
    flag: 'https://media.api-sports.io/flags/co.svg',
  },
  {
    name: 'Ecuador',
    nameCode: 'ecuador',
    code: 'EC',
    flag: 'https://media.api-sports.io/flags/ec.svg',
  },
  {
    name: 'England',
    nameCode: 'england',
    code: 'GB',
    flag: 'https://media.api-sports.io/flags/gb.svg',
  },
  {
    name: 'France',
    nameCode: 'france',
    code: 'FR',
    flag: 'https://media.api-sports.io/flags/fr.svg',
  },
  {
    name: 'Germany',
    nameCode: 'germany',
    code: 'DE',
    flag: 'https://media.api-sports.io/flags/de.svg',
  },
  {
    name: 'Greece',
    nameCode: 'greece',
    code: 'GR',
    flag: 'https://media.api-sports.io/flags/gr.svg',
  },
  {
    name: 'Italy',
    nameCode: 'italy',
    code: 'IT',
    flag: 'https://media.api-sports.io/flags/it.svg',
  },
  {
    name: 'Mexico',
    nameCode: 'mexico',
    code: 'MX',
    flag: 'https://media.api-sports.io/flags/mx.svg',
  },
  {
    name: 'Netherlands',
    nameCode: 'netherlands',
    code: 'NL',
    flag: 'https://media.api-sports.io/flags/nl.svg',
  },
  {
    name: 'Paraguay',
    nameCode: 'paraguay',
    code: 'PY',
    flag: 'https://media.api-sports.io/flags/py.svg',
  },
  { name: 'Peru', nameCode: 'peru', code: 'PE', flag: 'https://media.api-sports.io/flags/pe.svg' },
  {
    name: 'Portugal',
    nameCode: 'portugal',
    code: 'PT',
    flag: 'https://media.api-sports.io/flags/pt.svg',
  },
  {
    name: 'Spain',
    nameCode: 'spain',
    code: 'ES',
    flag: 'https://media.api-sports.io/flags/es.svg',
  },
  {
    name: 'Turkey',
    nameCode: 'turkey',
    code: 'TR',
    flag: 'https://media.api-sports.io/flags/tr.svg',
  },
  {
    name: 'Uruguay',
    nameCode: 'uruguay',
    code: 'UY',
    flag: 'https://media.api-sports.io/flags/uy.svg',
  },
  { name: 'USA', nameCode: 'usa', code: 'US', flag: 'https://media.api-sports.io/flags/us.svg' },
  { name: 'World', nameCode: 'world', code: 'WORLD', flag: '/globe.svg' },
]

export const ALL_COUNTRIES: Country[] = [
  {
    name: 'Albania',
    nameCode: 'albania',
    code: 'AL',
    flag: 'https://media.api-sports.io/flags/al.svg',
  },
  {
    name: 'Algeria',
    nameCode: 'algeria',
    code: 'DZ',
    flag: 'https://media.api-sports.io/flags/dz.svg',
  },
  {
    name: 'Andorra',
    nameCode: 'andorra',
    code: 'AD',
    flag: 'https://media.api-sports.io/flags/ad.svg',
  },
  {
    name: 'Angola',
    nameCode: 'angola',
    code: 'AO',
    flag: 'https://media.api-sports.io/flags/ao.svg',
  },
  {
    name: 'Antigua-And-Barbuda',
    nameCode: 'antigua_and_barbuda',
    code: 'AG',
    flag: 'https://media.api-sports.io/flags/ag.svg',
  },
  {
    name: 'Argentina',
    nameCode: 'argentina',
    code: 'AR',
    flag: 'https://media.api-sports.io/flags/ar.svg',
  },
  {
    name: 'Armenia',
    nameCode: 'armenia',
    code: 'AM',
    flag: 'https://media.api-sports.io/flags/am.svg',
  },
  {
    name: 'Aruba',
    nameCode: 'aruba',
    code: 'AW',
    flag: 'https://media.api-sports.io/flags/aw.svg',
  },
  {
    name: 'Australia',
    nameCode: 'australia',
    code: 'AU',
    flag: 'https://media.api-sports.io/flags/au.svg',
  },
  {
    name: 'Austria',
    nameCode: 'austria',
    code: 'AT',
    flag: 'https://media.api-sports.io/flags/at.svg',
  },
  {
    name: 'Azerbaijan',
    nameCode: 'azerbaijan',
    code: 'AZ',
    flag: 'https://media.api-sports.io/flags/az.svg',
  },
  {
    name: 'Bahrain',
    nameCode: 'bahrain',
    code: 'BH',
    flag: 'https://media.api-sports.io/flags/bh.svg',
  },
  {
    name: 'Bangladesh',
    nameCode: 'bangladesh',
    code: 'BD',
    flag: 'https://media.api-sports.io/flags/bd.svg',
  },
  {
    name: 'Barbados',
    nameCode: 'barbados',
    code: 'BB',
    flag: 'https://media.api-sports.io/flags/bb.svg',
  },
  {
    name: 'Belarus',
    nameCode: 'belarus',
    code: 'BY',
    flag: 'https://media.api-sports.io/flags/by.svg',
  },
  {
    name: 'Belgium',
    nameCode: 'belgium',
    code: 'BE',
    flag: 'https://media.api-sports.io/flags/be.svg',
  },
  {
    name: 'Belize',
    nameCode: 'belize',
    code: 'BZ',
    flag: 'https://media.api-sports.io/flags/bz.svg',
  },
  {
    name: 'Benin',
    nameCode: 'benin',
    code: 'BJ',
    flag: 'https://media.api-sports.io/flags/bj.svg',
  },
  {
    name: 'Bermuda',
    nameCode: 'bermuda',
    code: 'BM',
    flag: 'https://media.api-sports.io/flags/bm.svg',
  },
  {
    name: 'Bhutan',
    nameCode: 'bhutan',
    code: 'BT',
    flag: 'https://media.api-sports.io/flags/bt.svg',
  },
  {
    name: 'Bolivia',
    nameCode: 'bolivia',
    code: 'BO',
    flag: 'https://media.api-sports.io/flags/bo.svg',
  },
  {
    name: 'Bosnia',
    nameCode: 'bosnia',
    code: 'BA',
    flag: 'https://media.api-sports.io/flags/ba.svg',
  },
  {
    name: 'Botswana',
    nameCode: 'botswana',
    code: 'BW',
    flag: 'https://media.api-sports.io/flags/bw.svg',
  },
  {
    name: 'Brazil',
    nameCode: 'brazil',
    code: 'BR',
    flag: 'https://media.api-sports.io/flags/br.svg',
  },
  {
    name: 'Bulgaria',
    nameCode: 'bulgaria',
    code: 'BG',
    flag: 'https://media.api-sports.io/flags/bg.svg',
  },
  {
    name: 'Burkina-Faso',
    nameCode: 'burkina_faso',
    code: 'BF',
    flag: 'https://media.api-sports.io/flags/bf.svg',
  },
  {
    name: 'Burundi',
    nameCode: 'burundi',
    code: 'BI',
    flag: 'https://media.api-sports.io/flags/bi.svg',
  },
  {
    name: 'Cambodia',
    nameCode: 'cambodia',
    code: 'KH',
    flag: 'https://media.api-sports.io/flags/kh.svg',
  },
  {
    name: 'Cameroon',
    nameCode: 'cameroon',
    code: 'CM',
    flag: 'https://media.api-sports.io/flags/cm.svg',
  },
  {
    name: 'Canada',
    nameCode: 'canada',
    code: 'CA',
    flag: 'https://media.api-sports.io/flags/ca.svg',
  },
  {
    name: 'Chile',
    nameCode: 'chile',
    code: 'CL',
    flag: 'https://media.api-sports.io/flags/cl.svg',
  },
  {
    name: 'China',
    nameCode: 'china',
    code: 'CN',
    flag: 'https://media.api-sports.io/flags/cn.svg',
  },
  {
    name: 'Chinese-Taipei',
    nameCode: 'chinese_taipei',
    code: 'TW',
    flag: 'https://media.api-sports.io/flags/tw.svg',
  },
  {
    name: 'Colombia',
    nameCode: 'colombia',
    code: 'CO',
    flag: 'https://media.api-sports.io/flags/co.svg',
  },
  {
    name: 'Congo',
    nameCode: 'republic_of_the_congo',
    code: 'CD',
    flag: 'https://media.api-sports.io/flags/cd.svg',
  },
  {
    name: 'Congo-DR',
    nameCode: 'congo_dr',
    code: 'CG',
    flag: 'https://media.api-sports.io/flags/cg.svg',
  },
  {
    name: 'Costa Rica',
    nameCode: 'costarica',
    code: 'CR',
    flag: 'https://media.api-sports.io/flags/cr.svg',
  },
  {
    name: 'Crimea',
    nameCode: 'crimea',
    code: 'UA',
    flag: 'https://media.api-sports.io/flags/ua.svg',
  },
  {
    name: 'Croatia',
    nameCode: 'croatia',
    code: 'HR',
    flag: 'https://media.api-sports.io/flags/hr.svg',
  },
  {
    name: 'Cuba',
    nameCode: 'cuba',
    code: 'CU',
    flag: 'https://media.api-sports.io/flags/cu.svg',
  },
  {
    name: 'Curacao',
    nameCode: 'curacao',
    code: 'CW',
    flag: 'https://media.api-sports.io/flags/cw.svg',
  },
  {
    name: 'Cyprus',
    nameCode: 'cyprus',
    code: 'CY',
    flag: 'https://media.api-sports.io/flags/cy.svg',
  },
  {
    name: 'Czech-Republic',
    nameCode: 'czech_republic',
    code: 'CZ',
    flag: 'https://media.api-sports.io/flags/cz.svg',
  },
  {
    name: 'Denmark',
    nameCode: 'denmark',
    code: 'DK',
    flag: 'https://media.api-sports.io/flags/dk.svg',
  },
  {
    name: 'Dominican-Republic',
    nameCode: 'dominican_republic',
    code: 'DO',
    flag: 'https://media.api-sports.io/flags/do.svg',
  },
  {
    name: 'Ecuador',
    nameCode: 'equador',
    code: 'EC',
    flag: 'https://media.api-sports.io/flags/ec.svg',
  },
  {
    name: 'Egypt',
    nameCode: 'egypt',
    code: 'EG',
    flag: 'https://media.api-sports.io/flags/eg.svg',
  },
  {
    name: 'El-Salvador',
    nameCode: 'el_salvador',
    code: 'SV',
    flag: 'https://media.api-sports.io/flags/sv.svg',
  },
  {
    name: 'England',
    nameCode: 'england',
    code: 'GB-ENG',
    flag: 'https://media.api-sports.io/flags/gb-eng.svg',
  },
  {
    name: 'Estonia',
    nameCode: 'estonia',
    code: 'EE',
    flag: 'https://media.api-sports.io/flags/ee.svg',
  },
  {
    name: 'Eswatini',
    nameCode: 'eswatini',
    code: 'SZ',
    flag: 'https://media.api-sports.io/flags/sz.svg',
  },
  {
    name: 'Ethiopia',
    nameCode: 'ethiopia',
    code: 'ET',
    flag: 'https://media.api-sports.io/flags/et.svg',
  },
  {
    name: 'Faroe-Islands',
    nameCode: 'faroe_islands',
    code: 'FO',
    flag: 'https://media.api-sports.io/flags/fo.svg',
  },
  {
    name: 'Fiji',
    nameCode: 'fiji',
    code: 'FJ',
    flag: 'https://media.api-sports.io/flags/fj.svg',
  },
  {
    name: 'Finland',
    nameCode: 'finland',
    code: 'FI',
    flag: 'https://media.api-sports.io/flags/fi.svg',
  },
  {
    name: 'France',
    nameCode: 'france',
    code: 'FR',
    flag: 'https://media.api-sports.io/flags/fr.svg',
  },
  {
    name: 'Gabon',
    nameCode: 'gabon',
    code: 'GA',
    flag: 'https://media.api-sports.io/flags/ga.svg',
  },
  {
    name: 'Gambia',
    nameCode: 'gambia',
    code: 'GM',
    flag: 'https://media.api-sports.io/flags/gm.svg',
  },
  {
    name: 'Georgia',
    nameCode: 'georgia',
    code: 'GE',
    flag: 'https://media.api-sports.io/flags/ge.svg',
  },
  {
    name: 'Germany',
    nameCode: 'germany',
    code: 'DE',
    flag: 'https://media.api-sports.io/flags/de.svg',
  },
  {
    name: 'Ghana',
    nameCode: 'ghana',
    code: 'GH',
    flag: 'https://media.api-sports.io/flags/gh.svg',
  },
  {
    name: 'Gibraltar',
    nameCode: 'gibraltar',
    code: 'GI',
    flag: 'https://media.api-sports.io/flags/gi.svg',
  },
  {
    name: 'Greece',
    nameCode: 'greece',
    code: 'GR',
    flag: 'https://media.api-sports.io/flags/gr.svg',
  },
  {
    name: 'Grenada',
    nameCode: 'grenada',
    code: 'GD',
    flag: 'https://media.api-sports.io/flags/gd.svg',
  },
  {
    name: 'Guadeloupe',
    nameCode: 'guadeloupe',
    code: 'GP',
    flag: 'https://media.api-sports.io/flags/gp.svg',
  },
  {
    name: 'Guatemala',
    nameCode: 'guatemala',
    code: 'GT',
    flag: 'https://media.api-sports.io/flags/gt.svg',
  },
  {
    name: 'Guinea',
    nameCode: 'guinea',
    code: 'GN',
    flag: 'https://media.api-sports.io/flags/gn.svg',
  },
  {
    name: 'Haiti',
    nameCode: 'haiti',
    code: 'HT',
    flag: 'https://media.api-sports.io/flags/ht.svg',
  },
  {
    name: 'Honduras',
    nameCode: 'honduras',
    code: 'HN',
    flag: 'https://media.api-sports.io/flags/hn.svg',
  },
  {
    name: 'Hong-Kong',
    nameCode: 'hong_kong',
    code: 'HK',
    flag: 'https://media.api-sports.io/flags/hk.svg',
  },
  {
    name: 'Hungary',
    nameCode: 'hungary',
    code: 'HU',
    flag: 'https://media.api-sports.io/flags/hu.svg',
  },
  {
    name: 'Iceland',
    nameCode: 'iceland',
    code: 'IS',
    flag: 'https://media.api-sports.io/flags/is.svg',
  },
  {
    name: 'India',
    nameCode: 'india',
    code: 'IN',
    flag: 'https://media.api-sports.io/flags/in.svg',
  },
  {
    name: 'Indonesia',
    nameCode: 'indonesia',
    code: 'ID',
    flag: 'https://media.api-sports.io/flags/id.svg',
  },
  {
    name: 'Iran',
    nameCode: 'iran',
    code: 'IR',
    flag: 'https://media.api-sports.io/flags/ir.svg',
  },
  {
    name: 'Iraq',
    nameCode: 'iraq',
    code: 'IQ',
    flag: 'https://media.api-sports.io/flags/iq.svg',
  },
  {
    name: 'Ireland',
    nameCode: 'ireland',
    code: 'IE',
    flag: 'https://media.api-sports.io/flags/ie.svg',
  },
  {
    name: 'Israel',
    nameCode: 'israel',
    code: 'IL',
    flag: 'https://media.api-sports.io/flags/il.svg',
  },
  {
    name: 'Italy',
    nameCode: 'italy',
    code: 'IT',
    flag: 'https://media.api-sports.io/flags/it.svg',
  },
  {
    name: 'Ivory-Coast',
    nameCode: 'ivory_coast',
    code: 'CI',
    flag: 'https://media.api-sports.io/flags/ci.svg',
  },
  {
    name: 'Jamaica',
    nameCode: 'jamaica',
    code: 'JM',
    flag: 'https://media.api-sports.io/flags/jm.svg',
  },
  {
    name: 'Japan',
    nameCode: 'japan',
    code: 'JP',
    flag: 'https://media.api-sports.io/flags/jp.svg',
  },
  {
    name: 'Jordan',
    nameCode: 'jordan',
    code: 'JO',
    flag: 'https://media.api-sports.io/flags/jo.svg',
  },
  {
    name: 'Kazakhstan',
    nameCode: 'kazakhstan',
    code: 'KZ',
    flag: 'https://media.api-sports.io/flags/kz.svg',
  },
  {
    name: 'Kenya',
    nameCode: 'kenya',
    code: 'KE',
    flag: 'https://media.api-sports.io/flags/ke.svg',
  },
  {
    name: 'Kosovo',
    nameCode: 'kosovo',
    code: 'XK',
    flag: 'https://media.api-sports.io/flags/xk.svg',
  },
  {
    name: 'Kuwait',
    nameCode: 'kuwait',
    code: 'KW',
    flag: 'https://media.api-sports.io/flags/kw.svg',
  },
  {
    name: 'Kyrgyzstan',
    nameCode: 'kyrgyzstan',
    code: 'KG',
    flag: 'https://media.api-sports.io/flags/kg.svg',
  },
  {
    name: 'Laos',
    nameCode: 'laos',
    code: 'LA',
    flag: 'https://media.api-sports.io/flags/la.svg',
  },
  {
    name: 'Latvia',
    nameCode: 'latvia',
    code: 'LV',
    flag: 'https://media.api-sports.io/flags/lv.svg',
  },
  {
    name: 'Lebanon',
    nameCode: 'lebanon',
    code: 'LB',
    flag: 'https://media.api-sports.io/flags/lb.svg',
  },
  {
    name: 'Lesotho',
    nameCode: 'lesotho',
    code: 'LS',
    flag: 'https://media.api-sports.io/flags/ls.svg',
  },
  {
    name: 'Liberia',
    nameCode: 'liberia',
    code: 'LR',
    flag: 'https://media.api-sports.io/flags/lr.svg',
  },
  {
    name: 'Libya',
    nameCode: 'libya',
    code: 'LY',
    flag: 'https://media.api-sports.io/flags/ly.svg',
  },
  {
    name: 'Liechtenstein',
    nameCode: 'liechtenstein',
    code: 'LI',
    flag: 'https://media.api-sports.io/flags/li.svg',
  },
  {
    name: 'Lithuania',
    nameCode: 'lithuania',
    code: 'LT',
    flag: 'https://media.api-sports.io/flags/lt.svg',
  },
  {
    name: 'Luxembourg',
    nameCode: 'luxembourg',
    code: 'LU',
    flag: 'https://media.api-sports.io/flags/lu.svg',
  },
  {
    name: 'Macao',
    nameCode: 'macao',
    code: 'MO',
    flag: 'https://media.api-sports.io/flags/mo.svg',
  },
  {
    name: 'Macedonia',
    nameCode: 'macedonia',
    code: 'MK',
    flag: 'https://media.api-sports.io/flags/mk.svg',
  },
  {
    name: 'Malawi',
    nameCode: 'malawi',
    code: 'MW',
    flag: 'https://media.api-sports.io/flags/mw.svg',
  },
  {
    name: 'Malaysia',
    nameCode: 'malaysia',
    code: 'MY',
    flag: 'https://media.api-sports.io/flags/my.svg',
  },
  {
    name: 'Maldives',
    nameCode: 'maldives',
    code: 'MV',
    flag: 'https://media.api-sports.io/flags/mv.svg',
  },
  {
    name: 'Mali',
    nameCode: 'mali',
    code: 'ML',
    flag: 'https://media.api-sports.io/flags/ml.svg',
  },
  {
    name: 'Malta',
    nameCode: 'malta',
    code: 'MT',
    flag: 'https://media.api-sports.io/flags/mt.svg',
  },
  {
    name: 'Mauritania',
    nameCode: 'mauritania',
    code: 'MR',
    flag: 'https://media.api-sports.io/flags/mr.svg',
  },
  {
    name: 'Mauritius',
    nameCode: 'mauritius',
    code: 'MU',
    flag: 'https://media.api-sports.io/flags/mu.svg',
  },
  {
    name: 'Mexico',
    nameCode: 'mexico',
    code: 'MX',
    flag: 'https://media.api-sports.io/flags/mx.svg',
  },
  {
    name: 'Moldova',
    nameCode: 'moldova',
    code: 'MD',
    flag: 'https://media.api-sports.io/flags/md.svg',
  },
  {
    name: 'Mongolia',
    nameCode: 'mongolia',
    code: 'MN',
    flag: 'https://media.api-sports.io/flags/mn.svg',
  },
  {
    name: 'Montenegro',
    nameCode: 'montenegro',
    code: 'ME',
    flag: 'https://media.api-sports.io/flags/me.svg',
  },
  {
    name: 'Morocco',
    nameCode: 'morocco',
    code: 'MA',
    flag: 'https://media.api-sports.io/flags/ma.svg',
  },
  {
    name: 'Myanmar',
    nameCode: 'myanmar',
    code: 'MM',
    flag: 'https://media.api-sports.io/flags/mm.svg',
  },
  {
    name: 'Namibia',
    nameCode: 'namibia',
    code: 'NA',
    flag: 'https://media.api-sports.io/flags/na.svg',
  },
  {
    name: 'Nepal',
    nameCode: 'nepal',
    code: 'NP',
    flag: 'https://media.api-sports.io/flags/np.svg',
  },
  {
    name: 'Netherlands',
    nameCode: 'holland',
    code: 'NL',
    flag: 'https://media.api-sports.io/flags/nl.svg',
  },
  {
    name: 'New-Zealand',
    nameCode: 'new_zealand',
    code: 'NZ',
    flag: 'https://media.api-sports.io/flags/nz.svg',
  },
  {
    name: 'Nicaragua',
    nameCode: 'nicaragua',
    code: 'NI',
    flag: 'https://media.api-sports.io/flags/ni.svg',
  },
  {
    name: 'Nigeria',
    nameCode: 'nigeria',
    code: 'NG',
    flag: 'https://media.api-sports.io/flags/ng.svg',
  },
  {
    name: 'Northern-Ireland',
    nameCode: 'northern_ireland',
    code: 'GB-NIR',
    flag: 'https://media.api-sports.io/flags/gb-nir.svg',
  },
  {
    name: 'Norway',
    nameCode: 'norway',
    code: 'NO',
    flag: 'https://media.api-sports.io/flags/no.svg',
  },
  {
    name: 'Oman',
    nameCode: 'oman',
    code: 'OM',
    flag: 'https://media.api-sports.io/flags/om.svg',
  },
  {
    name: 'Pakistan',
    nameCode: 'pakistan',
    code: 'PK',
    flag: 'https://media.api-sports.io/flags/pk.svg',
  },
  {
    name: 'Palestine',
    nameCode: 'palestine',
    code: 'PS',
    flag: 'https://media.api-sports.io/flags/ps.svg',
  },
  {
    name: 'Panama',
    nameCode: 'panama',
    code: 'PA',
    flag: 'https://media.api-sports.io/flags/pa.svg',
  },
  {
    name: 'Paraguay',
    nameCode: 'paraguay',
    code: 'PY',
    flag: 'https://media.api-sports.io/flags/py.svg',
  },
  {
    name: 'Peru',
    nameCode: 'peru',
    code: 'PE',
    flag: 'https://media.api-sports.io/flags/pe.svg',
  },
  {
    name: 'Philippines',
    nameCode: 'philippines',
    code: 'PH',
    flag: 'https://media.api-sports.io/flags/ph.svg',
  },
  {
    name: 'Poland',
    nameCode: 'poland',
    code: 'PL',
    flag: 'https://media.api-sports.io/flags/pl.svg',
  },
  {
    name: 'Portugal',
    nameCode: 'portugal',
    code: 'PT',
    flag: 'https://media.api-sports.io/flags/pt.svg',
  },
  {
    name: 'Qatar',
    nameCode: 'qatar',
    code: 'QA',
    flag: 'https://media.api-sports.io/flags/qa.svg',
  },
  {
    name: 'Romania',
    nameCode: 'romania',
    code: 'RO',
    flag: 'https://media.api-sports.io/flags/ro.svg',
  },
  {
    name: 'Russia',
    nameCode: 'russia',
    code: 'RU',
    flag: 'https://media.api-sports.io/flags/ru.svg',
  },
  {
    name: 'Rwanda',
    nameCode: 'rwanda',
    code: 'RW',
    flag: 'https://media.api-sports.io/flags/rw.svg',
  },
  {
    name: 'San-Marino',
    nameCode: 'san_marino',
    code: 'SM',
    flag: 'https://media.api-sports.io/flags/sm.svg',
  },
  {
    name: 'Saudi-Arabia',
    nameCode: 'saudi_arabia',
    code: 'SA',
    flag: 'https://media.api-sports.io/flags/sa.svg',
  },
  {
    name: 'Scotland',
    nameCode: 'scotland',
    code: 'GB-SCT',
    flag: 'https://media.api-sports.io/flags/gb-sct.svg',
  },
  {
    name: 'Senegal',
    nameCode: 'senegal',
    code: 'SN',
    flag: 'https://media.api-sports.io/flags/sn.svg',
  },
  {
    name: 'Serbia',
    nameCode: 'serbia',
    code: 'RS',
    flag: 'https://media.api-sports.io/flags/rs.svg',
  },
  {
    name: 'Singapore',
    nameCode: 'singapore',
    code: 'SG',
    flag: 'https://media.api-sports.io/flags/sg.svg',
  },
  {
    name: 'Slovakia',
    nameCode: 'slovakia',
    code: 'SK',
    flag: 'https://media.api-sports.io/flags/sk.svg',
  },
  {
    name: 'Slovenia',
    nameCode: 'slovenia',
    code: 'SI',
    flag: 'https://media.api-sports.io/flags/si.svg',
  },
  {
    name: 'Somalia',
    nameCode: 'somalia',
    code: 'SO',
    flag: 'https://media.api-sports.io/flags/so.svg',
  },
  {
    name: 'South-Africa',
    nameCode: 'southafrica',
    code: 'ZA',
    flag: 'https://media.api-sports.io/flags/za.svg',
  },
  {
    name: 'South-Korea',
    nameCode: 'south_korea',
    code: 'KR',
    flag: 'https://media.api-sports.io/flags/kr.svg',
  },
  {
    name: 'Spain',
    nameCode: 'spain',
    code: 'ES',
    flag: 'https://media.api-sports.io/flags/es.svg',
  },
  {
    name: 'Sudan',
    nameCode: 'sudan',
    code: 'SD',
    flag: 'https://media.api-sports.io/flags/sd.svg',
  },
  {
    name: 'Suriname',
    nameCode: 'suriname',
    code: 'SR',
    flag: 'https://media.api-sports.io/flags/sr.svg',
  },
  {
    name: 'Sweden',
    nameCode: 'sweden',
    code: 'SE',
    flag: 'https://media.api-sports.io/flags/se.svg',
  },
  {
    name: 'Switzerland',
    nameCode: 'switzerland',
    code: 'CH',
    flag: 'https://media.api-sports.io/flags/ch.svg',
  },
  {
    name: 'Syria',
    nameCode: 'syria',
    code: 'SY',
    flag: 'https://media.api-sports.io/flags/sy.svg',
  },
  {
    name: 'Tajikistan',
    nameCode: 'tajikistan',
    code: 'TJ',
    flag: 'https://media.api-sports.io/flags/tj.svg',
  },
  {
    name: 'Tanzania',
    nameCode: 'tanzania',
    code: 'TZ',
    flag: 'https://media.api-sports.io/flags/tz.svg',
  },
  {
    name: 'Thailand',
    nameCode: 'thailand',
    code: 'TH',
    flag: 'https://media.api-sports.io/flags/th.svg',
  },
  {
    name: 'Togo',
    nameCode: 'togo',
    code: 'TG',
    flag: 'https://media.api-sports.io/flags/tg.svg',
  },
  {
    name: 'Trinidad-And-Tobago',
    nameCode: 'trinidad_and_tobago',
    code: 'TT',
    flag: 'https://media.api-sports.io/flags/tt.svg',
  },
  {
    name: 'Tunisia',
    nameCode: 'tunisia',
    code: 'TN',
    flag: 'https://media.api-sports.io/flags/tn.svg',
  },
  {
    name: 'Turkey',
    nameCode: 'turkey',
    code: 'TR',
    flag: 'https://media.api-sports.io/flags/tr.svg',
  },
  {
    name: 'Turkmenistan',
    nameCode: 'turkmenistan',
    code: 'TM',
    flag: 'https://media.api-sports.io/flags/tm.svg',
  },
  {
    name: 'Uganda',
    nameCode: 'uganda',
    code: 'UG',
    flag: 'https://media.api-sports.io/flags/ug.svg',
  },
  {
    name: 'Ukraine',
    nameCode: 'ukraine',
    code: 'UA',
    flag: 'https://media.api-sports.io/flags/ua.svg',
  },
  {
    name: 'United-Arab-Emirates',
    nameCode: 'united_arab_emirates',
    code: 'AE',
    flag: 'https://media.api-sports.io/flags/ae.svg',
  },
  {
    name: 'Uruguay',
    nameCode: 'uruguay',
    code: 'UY',
    flag: 'https://media.api-sports.io/flags/uy.svg',
  },
  {
    name: 'USA',
    nameCode: 'usa',
    code: 'US',
    flag: 'https://media.api-sports.io/flags/us.svg',
  },
  {
    name: 'Uzbekistan',
    nameCode: 'uzbekistan',
    code: 'UZ',
    flag: 'https://media.api-sports.io/flags/uz.svg',
  },
  {
    name: 'Venezuela',
    nameCode: 'venezuela',
    code: 'VE',
    flag: 'https://media.api-sports.io/flags/ve.svg',
  },
  {
    name: 'Vietnam',
    nameCode: 'vietnam',
    code: 'VN',
    flag: 'https://media.api-sports.io/flags/vn.svg',
  },
  {
    name: 'Wales',
    nameCode: 'wales',
    code: 'GB-WLS',
    flag: 'https://media.api-sports.io/flags/gb-wls.svg',
  },
  {
    name: 'World',
    nameCode: 'world',
    code: 'WORLD',
    flag: '/globe.svg',
  },
  {
    name: 'Yemen',
    nameCode: 'yemen',
    code: 'YE',
    flag: 'https://media.api-sports.io/flags/ye.svg',
  },
  {
    name: 'Zambia',
    nameCode: 'zambia',
    code: 'ZM',
    flag: 'https://media.api-sports.io/flags/zm.svg',
  },
  {
    name: 'Zimbabwe',
    nameCode: 'zimbabwe',
    code: 'ZW',
    flag: 'https://media.api-sports.io/flags/zw.svg',
  },
  // NO FLAGS FOUNDED
  // martinique, bosnian and herzegovina
  {
    name: 'Martinique',
    nameCode: 'martinique',
    code: 'MQ',
    flag: 'https://flagpedia.net/data/flags/w580/mq.webp',
  },
  {
    name: 'Bosnia and Herzegovina',
    nameCode: 'bosnia_and_herzegovina',
    code: 'BA',
    flag: 'https://flagpedia.net/data/flags/w580/ba.webp',
  }, 
]
